[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/robostack-jazzy",
  "https://prefix.dev/conda-forge",
]
name = "lanelet2"
platforms = ["linux-64", "osx-arm64", "win-64"]
preview = ["pixi-build"]

[dependencies]
ros-jazzy-lanelet2 = { path = "lanelet2/package.xml" }
ros-jazzy-lanelet2-core = { path = "lanelet2_core/package.xml" }
ros-jazzy-lanelet2-examples = { path = "lanelet2_examples/package.xml" }
ros-jazzy-lanelet2-io = { path = "lanelet2_io/package.xml" }
ros-jazzy-lanelet2-maps = { path = "lanelet2_maps/package.xml" }
ros-jazzy-lanelet2-matching = { path = "lanelet2_matching/package.xml" }
ros-jazzy-lanelet2-projection = { path = "lanelet2_projection/package.xml" }
ros-jazzy-lanelet2-python = { path = "lanelet2_python/package.xml" }
ros-jazzy-lanelet2-routing = { path = "lanelet2_routing/package.xml" }
ros-jazzy-lanelet2-traffic-rules = { path = "lanelet2_traffic_rules/package.xml" }
ros-jazzy-lanelet2-validation = { path = "lanelet2_validation/package.xml" }
